Repository circuitikz/circuitikz, pull requests merged in 2019-05, with the labels that each got.

#203 Fix/workaround label position in some corner case
  CHANGELOG.md
  tex/pgfcirclabel.tex
Labels: Work in progress

#206 Changed the anchors for chips to fix bug #205
  tex/pgfcircmultipoles.tex
  tex/pgfcirctripoles.tex
Labels: bug

#200 [WIP] Improvements to the manual
  doc/.gitignore
  doc/circuitikzmanual.tex
Labels: enhancement

#208 Add the option to have inline quadpoles
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/pgfcirc.defines.tex
  tex/pgfcircquadpoles.tex
Labels: enhancement
