Repository circuitikz/circuitikz, pull requests merged in 2020-10, with the labels that each got.

#446 add resistive splitter
  doc/circuitikzmanual.tex
  tex/pgfcirc.defines.tex
  tex/pgfcircquadpoles.tex
Labels: enhancement

#449 Added symbols for depletion-mode MOSFETs
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/pgfcirc.defines.tex
  tex/pgfcircpath.tex
  tex/pgfcirctripoles.tex
Labels: enhancement, new component

#450 * Version 1.2.4 (2020-10-04)
  CHANGELOG.md
  tex/circuitikz.sty
  tex/t-circuitikz.tex
Labels: release prep

#452 Label and annotation information retrieval
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/circuitikz.sty
  tex/pgfcirclabel.tex
  tex/t-circuitikz.tex
Labels: enhancement

#453 Fix a bug in "raised" voltage positioning
  CHANGELOG.md
  tex/pgfcircvoltage.tex
Labels: bug

#454 Prepare release 1.2.5
  CHANGELOG.md
  tex/circuitikz.sty
  tex/t-circuitikz.tex
Labels: release prep

#455 Bump version number for continuing development
  CHANGELOG.md
  tex/circuitikz.sty
  tex/t-circuitikz.tex
Labels: release prep

#456 Fix typo in the manual
  doc/circuitikzmanual.tex
Labels: documentation bug
