Repository circuitikz/circuitikz, pull requests merged in 2020-05, with the labels that each got.

#396 Powerelectronics
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/pgfcirc.defines.tex
  tex/pgfcircbipoles.tex
  tex/pgfcircpath.tex
  tex/pgfcircquadpoles.tex
Labels: enhancement

#400 Fix position of open circuit american voltages
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/pgfcirc.defines.tex
  tex/pgfcircvoltage.tex
Labels: enhancement

#401 Fix superposed thickness in european not circles
  tex/pgfcirctripoles.tex
Labels: bug

#404 Logic fixes
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/pgfcirc.defines.tex
  tex/pgfcircmultipoles.tex
  tex/pgfcirctripoles.tex
Labels: bug, enhancement

#407 Path style not
  CHANGELOG.md
  doc/circuitikzmanual.tex
  doc/ctikzmanutils.sty
  tex/pgfcircmultipoles.tex
  tex/pgfcircpath.tex
  tex/pgfcirctripoles.tex
Labels: enhancement
