Repository circuitikz/circuitikz, pull requests merged in 2021-06, with the labels that each got.

#547 * version 1.3.7 (2021-06-01)
  CHANGELOG.md
  tex/circuitikz.sty
  tex/t-circuitikz.tex
Labels: release prep

#548 Make dipchip and qfpchip respect the "no input leads" setting
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/circuitikz.sty
  tex/pgfcircmultipoles.tex
  tex/t-circuitikz.tex
Labels: enhancement

#550 Select pins in dipchip
  doc/circuitikzmanual.tex
  tex/pgfcircmultipoles.tex
  tex/pgfcircutils.tex
Labels: enhancement

#551 Extend "draw only pins" to qfpchips and muxdemuxes
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/pgfcircmultipoles.tex
Labels: enhancement

#552 Fixing warnings and typos in the manual
  doc/circuitikzmanual.tex
Labels: documentation bug/improvement

#554 Make the PR tests more ecological
  .travis.yml
  Makefile
  tools/check.sh
Labels: enhancement

#556 Warn that stacked labels works only in LaTeX
  doc/circuitikzmanual.tex
Labels: documentation bug/improvement

#557 CTAN release 1.3.8 (2021-06-15)
  CHANGELOG.md
  tex/circuitikz.sty
  tex/t-circuitikz.tex
Labels: release prep

#558 Minor fixes to the manual
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/circuitikz.sty
  tex/t-circuitikz.tex
Labels: documentation bug/improvement

#559 Bug in setting open poles opacity
  doc/circuitikzmanual.tex
  tex/pgfcircshapes.tex
Labels: bug

#560 Preparation for CTAN release 1.3.9 (2012-06-27)
  CHANGELOG.md
  tex/circuitikz.sty
Labels: release prep
