Repository circuitikz/circuitikz, pull requests merged in 2022-05, with the labels that each got.

#630 Add shapes for transorb (TVS diodes)
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/circuitikz.sty
  tex/pgfcircbipoles.tex
  tex/t-circuitikz.tex
Labels: new component

#632 Add proximeter shape and bipole
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/pgfcircbipoles.tex
Labels: new component

#634 CTAN release 1.5.2 (2022-05-08)
  CHANGELOG.md
  tex/circuitikz.sty
  tex/t-circuitikz.tex
Labels: release prep

#636 Modify example so that KCL box includes labels for all branch currents.
  doc/circuitikzmanual.tex
Labels: documentation bug/improvement

#635 Minor corrections to grammar, wording, and the like, through the end of the Introduction
  doc/circuitikzmanual.tex
Labels: documentation bug/improvement
