Repository circuitikz/circuitikz, pull requests merged in 2022-12, with the labels that each got.

#674 Hotfix for the new up/down anchors on amp and vamp
  tex/pgfcircquadpoles.tex
Labels: bug

#675 Add `genericspliter` component and scale splitter using `/tripoles/splitter/*`
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/pgfcircquadpoles.tex
Labels: bug, enhancement

#668 Fix typos
  doc/circuitikzmanual.tex
Labels: documentation bug/improvement

#676 Prepare for CTAN release 1.6.0 (2022-12-10)
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/circuitikz.sty
  tex/t-circuitikz.tex
Labels: release prep

#677 Refresh the README file a bit.
  README.md
  doc/circuitikzmanual.tex
  example_ctikz.png
Labels: documentation bug/improvement

#681 Add configurable dashes to the dc symbols in converter blocks
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/circuitikz.sty
  tex/pgfcircquadpoles.tex
  tex/t-circuitikz.tex
Labels: enhancement

#682 Remove the "experimental" notice for subcircuits
  CHANGELOG.md
  doc/circuitikzmanual.tex
Labels: documentation bug/improvement
