Repository circuitikz/circuitikz, pull requests merged in 2023-08, with the labels that each got.

#731 Unrotate text in European logic ports
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/pgfcirctripoles.tex
Labels: bug, enhancement

#734 Add some new Switches
  doc/circuitikzmanual.tex
  tex/pgfcircbipoles.tex
Labels: new component

#735 Configure switches arrow
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/pgfcircbipoles.tex
Labels: enhancement

#736 Homage to Randall Munroe's xkcd
  doc/circuitikzmanual.tex
  tex/pgfcircbipoles.tex
Labels: not-a-bug

#737 Add open shape to sinusoidal current source
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/pgfcircbipoles.tex
Labels: enhancement
