Repository circuitikz/circuitikz, pull requests merged in 2024-01, with the labels that each got.

#771 added optical fiber
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/pgfcircquadpoles.tex
Labels: new component

#772 Add related and enhancement packages to the documentation
  CHANGELOG.md
  doc/circuitikzmanual.tex
Labels: documentation bug/improvement

#775 Vsources sign rotation
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/ctikzstyle-romano.tex
  tex/pgfcircbipoles.tex
Labels: enhancement
