Repository circuitikz/circuitikz, pull requests merged in 2024-05, with the labels that each got.

#788 Multi anode triode
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/pgfcirctripoles.tex
Labels: new component

#789 Enhance documentation for instruments
  CHANGELOG.md
  doc/circuitikzmanual.tex
Labels: documentation bug/improvement

#791 Prepare release 1.6.8
  CHANGELOG.md
  tex/circuitikz.sty
  tex/t-circuitikz.tex
Labels: release prep

#795 Add Relais-Shape
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/pgfcircbipoles.tex
Labels: new component

#797 Fix a (long-standing) problem in switching diode type
  CHANGELOG.md
  tex/pgfcircbipoles.tex
  tex/pgfcirctripoles.tex
Labels: bug

#798 Add a center tap for tube's filament
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/pgfcirctripoles.tex
Labels: enhancement

#799 Add neon lamps, in two versions.
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/pgfcircbipoles.tex
Labels: new component

#801 Add spark gap
  CHANGELOG.md
  doc/circuitikzmanual.tex
  tex/pgfcircbipoles.tex
Labels: new component

#802 Release prep for version 1.6.9 (2024-05-25)
  CHANGELOG.md
  tex/circuitikz.sty
  tex/t-circuitikz.tex
Labels: release prep

#803 Bump version number
  doc/circuitikzmanual.tex
  tex/circuitikz.sty
  tex/t-circuitikz.tex
Labels: documentation bug/improvement

#804 Update Changelog
  CHANGELOG.md
Labels: documentation bug/improvement
